[project]
version = "1.0.6+as3b.3"
name = "homeconnect_ws"
authors = [{ name = "chris-mc1" }]
description = "Home Connect Local for Homeassistant"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = ["homeconnect-websocket==1.5.4"]

[project.urls]
Homepage = "https://github.com/chris-mc1/homeconnect_local_hass"
Issues = "https://github.com/chris-mc1/homeconnect_local_hass/issues"

[dependency-groups]
dev = [
    { include-group = "lint" },
    { include-group = "test" },
    "colorlog==6.12.0",
    "homeassistant==2026.8.1",
    "prek==0.5.3",
]
lint = ["ruff==0.16.9"]
test = ["pytest-homeassistant-custom-component"]

[tool.uv]
constraint-dependencies = ["cffi==2.0.0"]

[tool.coverage.run]
branch = true

[tool.coverage.report]
exclude_lines = ["if TYPE_CHECKING:"]

[tool.pytest.ini_options]
pythonpath = ["."]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"